Importing the necessary libraries

In [24]:
import pandas as pd
import numpy as np

Perpceptron Class definition

In [25]:
class Perceptron:
  # Initializing weights,learning rate aand epochs
  def __init__(self,eta,epochs):
    # Random Weight Assignment
    self.weights = np.random.randn(3) * 1e-4
    print("Initial weights",self.weights)
    self.eta = eta
    self.epochs = epochs


# Defining the Activation Function - using the step function
  def activationFunction(self,inputs,weights):
    # Multiplying weights and the input values 
    z = np.dot(inputs,weights)
    return np.where(z>0,1,0)

# Defining the Fit Method
  def fit(self,X,y):
    self.X=X
    self.y=y
    # Adding bias to the input values 
    X_with_bias = np.c_[self.X,-np.ones((len(self.X),1))]
    print("X with Bias ",X_with_bias)

    # Forward  & backward Propogation
    for epoch in range(self.epochs):
        
        print("====================")
        print("for epoch",epoch)
        print("====================")

        y_hat = self.activationFunction(X_with_bias,self.weights)
        print("predicted values",y_hat)
        self.error = self.y - y_hat
        # Early Stopping (basic implementation)
        #- Need to compare with previous error value in reality)
        if np.sum(self.error)==0:
            break
        # Weights updation 
        self.weights = self.weights + self.eta* np.dot(X_with_bias.T,self.error)
        print("Updated weights after epoch",self.epochs,self.weights)


# Defining the Predict Method
  def predict(self,X):
    X_with_bias = np.c_[self.X,-np.ones((len(self.X),1))]
    return self.activationFunction(X_with_bias,self.weights)

# Defining a method to calculate the loss
  def total_loss(self):
    total_loss = np.sum(self.error)
    print("Toal loss",total_loss)
    return total_loss


In [26]:
# A Method to separate the independent and Dependent features
def prepare_data(df):
    X=df.drop("y",axis=1)
    y=df['y']
  
    return X,y

In [27]:
# Populating Data to implement the AND Logic gate
AND ={
    
    "x1":[0,0,1,1],
    "x2":[0,1,0,1],
    "y":[0,0,0,1]
}

df = pd.DataFrame(AND)

In [28]:
X,y = prepare_data(df)

Training the Perceptron & Model Predictions

In [29]:
ETA=0.3  # Learning Rate
EPOCHS = 10 # Epochs

model = Perceptron(eta=ETA, epochs=EPOCHS)
model.fit(X,y)
model.total_loss()


Initial weights [-1.65836755e-06 -4.82264774e-05  1.39375260e-04]
X with Bias  [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch 0
predicted values [0 0 0 0]
Updated weights after epoch 10 [ 0.29999834  0.29995177 -0.29986062]
for epoch 1
predicted values [1 1 1 1]
Updated weights after epoch 10 [-1.65836755e-06 -4.82264774e-05  6.00139375e-01]
for epoch 2
predicted values [0 0 0 0]
Updated weights after epoch 10 [0.29999834 0.29995177 0.30013938]
for epoch 3
predicted values [0 0 0 1]
Toal loss 0


0

In [30]:
model.predict(X)

array([0, 0, 0, 1])