Importing the necessary libraries

In [1]:
import pandas as pd
import numpy as np

Perpceptron Class definition

In [2]:
class Perceptron:
  # Initializing weights,learning rate aand epochs
  def __init__(self,eta,epochs):
    # Random Weight Assignment
    self.weights = np.random.randn(3) * 1e-4
    print("Initial weights",self.weights)
    self.eta = eta
    self.epochs = epochs


# Defining the Activation Function - using the step function
  def activationFunction(self,inputs,weights):
    # Multiplying weights and the input values 
    z = np.dot(inputs,weights)
    return np.where(z>0,1,0)

# Defining the Fit Method
  def fit(self,X,y):
    self.X=X
    self.y=y
    # Adding bias to the input values 
    X_with_bias = np.c_[self.X,-np.ones((len(self.X),1))]
    print("X with Bias ",X_with_bias)

    # Forward  & backward Propogation
    for epoch in range(self.epochs):
          print("====================")
          print("for epoch",epoch)
          print("====================")

          y_hat = self.activationFunction(X_with_bias,self.weights)
          print("predicted values",y_hat)
          self.error = self.y - y_hat
          # Weights updation 
          self.weights = self.weights + self.eta* np.dot(X_with_bias.T,self.error)
          print("Updated weights after epoch",self.epochs,self.weights)


# Defining the Predict Method
  def predict(self,X):
    X_with_bias = np.c_[self.X,-np.ones((len(self.X),1))]
    return self.activationFunction(X_with_bias,self.weights)

# Defining a method to calculate the loss
  def total_loss(self):
    total_loss = np.sum(self.error)
    print("Toal loss",total_loss)
    return total_loss


In [3]:
# A Method to separate the independent and Dependent features
def prepare_data(df):
    X=df.drop("y",axis=1)
    y=df['y']
  
    return X,y

In [4]:
# Populating Data to implement the AND Logic gate
AND ={
    
    "x1":[0,0,1,1],
    "x2":[0,1,0,1],
    "y":[0,0,0,1]
}

df = pd.DataFrame(AND)

In [5]:
X,y = prepare_data(df)

Training the Perceptron & Model Predictions

In [6]:
ETA=0.3  # Learning Rate
EPOCHS = 10 # Epochs

model = Perceptron(eta=ETA, epochs=EPOCHS)
model.fit(X,y)
model.total_loss()


Initial weights [1.17572960e-04 1.07318631e-04 7.91509791e-05]
X with Bias  [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch 0
predicted values [0 1 1 1]
Updated weights after epoch 10 [-0.29988243 -0.29989268  0.60007915]
for epoch 1
predicted values [0 0 0 0]
Updated weights after epoch 10 [1.17572960e-04 1.07318631e-04 3.00079151e-01]
for epoch 2
predicted values [0 0 0 0]
Updated weights after epoch 10 [3.00117573e-01 3.00107319e-01 7.91509791e-05]
for epoch 3
predicted values [0 1 1 1]
Updated weights after epoch 10 [1.17572960e-04 1.07318631e-04 6.00079151e-01]
for epoch 4
predicted values [0 0 0 0]
Updated weights after epoch 10 [0.30011757 0.30010732 0.30007915]
for epoch 5
predicted values [0 1 1 1]
Updated weights after epoch 10 [1.17572960e-04 1.07318631e-04 9.00079151e-01]
for epoch 6
predicted values [0 0 0 0]
Updated weights after epoch 10 [0.30011757 0.30010732 0.60007915]
for epoch 7
predicted values [0 0 0 1]
Updated weights after epoch 10 [0.3001

0

In [7]:
model.predict(X)

array([0, 0, 0, 1])